name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Set AWS CLI region
      run: aws configure set region us-east-1

    - name: Set up AWS CLI
      run: |
       aws configure set region us-east-1
       aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
       aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      env:
       AWS_REGION: us-east-1
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


        
    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 477421128023.dkr.ecr.us-east-1.amazonaws.com



    - name: Build and push Docker image to AWS ECR
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ECR_REPO_URL: 477421128023.dkr.ecr.us-east-1.amazonaws.com/node-app-project-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
         docker build -t node-app-project-repo .
         docker tag node-app-project-repo:$IMAGE_TAG 477421128023.dkr.ecr.us-east-1.amazonaws.com/node-app-project-repo:$IMAGE_TAG
         docker push 477421128023.dkr.ecr.us-east-1.amazonaws.com/node-app-project-repo:$IMAGE_TAG

    - name: SSH into the server and deploy
      env:
        SERVER_IP: ${{ secrets.NGINX_SERVER_IP }}
        DOCKER_COMPOSE_PATH: /home/ubuntu/NodeJs-Dummy-App/docker-compose.yml
      run: |
        ssh -o StrictHostKeyChecking=no user@$SERVER_IP "docker-compose -f $DOCKER_COMPOSE_PATH pull"
        ssh -o StrictHostKeyChecking=no user@$SERVER_IP "docker-compose -f $DOCKER_COMPOSE_PATH up -d"
